obj-$(CONFIG_SENSORS) += sensors_core.o
obj-$(CONFIG_SENSORS_GP2A030A) += gp2ap030.o
obj-$(CONFIG_SENSORS_SX9500)   += sx9500.o
obj-$(CONFIG_SENSORS_AK8963C)   += ak8963c.o
obj-$(CONFIG_SENSORS_BMI055)    += bma255.o bmg160.o

