ccflags-y += -Idrivers/media/platform/msm/camera_v2_tabpro
ccflags-y += -Idrivers/media/platform/msm/camera_v2_tabpro/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
