ccflags-y += -Idrivers/media/platform/msm/camera_v2_tabpro
ccflags-y += -Idrivers/media/platform/msm/camera_v2_tabpro/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_tabpro/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
