ccflags-y += -Idrivers/media/platform/msm/camera_v2_tabpro
ccflags-y += -Idrivers/media/platform/msm/camera_v2_tabpro/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_tabpro/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
